import NavBar from "src/components/navbar";
import Head from "next/head";
import { api } from "~/utils/api";
import { useForm, type SubmitHandler } from "react-hook-form"
import { Textarea } from "@/components/ui/textarea"
import Image from 'next/image'
export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Machado</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="
      bg-gradient-radial from-black via-zinc-950 to-black
      flex min-h-screen flex-grow flex-col items-center ">
      <NavBar />
      <h1 className="text-6xl p-4 font-serif text-center font-bold bg-gradient-to-br from-violet-800 via-orange-600 to-indigo-700 bg-clip-text text-transparent">machado</h1>
    <Image 
          src="/Transparent_Machado_de_Assis.png"
          width={500}
          height={500}
          alt="Picture of the author"
    />
      </main>
    </>
  );
}


