import NavBar from "src/components/navbar";
import Head from "next/head";
import { api } from "~/utils/api";
import Image from 'next/image'

export default function Home() {

  return (
    <>
      <Head>
        <title>Machado</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="
      bg-gradient-radial from-black via-zinc-950 to-black
      flex min-h-screen flex-grow flex-col items-center ">
        <NavBar />

        <Image
          className=""
          src="/Transparent_Machado_de_Assis.png"
          width={350}
          height={350}
          alt="Picture of the author"
        />
        <h1 className="leading-none -mt-52 z-1 text-[330px] p-4 tracking-tighter font-oswald text-center font-bold 
    bg-gradient-to-tr from-rose-500 via-orange-600 to-fuchsia-400
    bg-clip-text text-transparent">
          assis
        </h1>
      </main>
    </>
  );
}


