import NavBar from "src/components/navbar";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Machado</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-grow flex-col items-center bg-gradient-to-b from-amber-600 to-slate-800">
      <NavBar />
      este site foi inspirado no livro Redação: escrever é desvendar o mundo
        <h1>intro</h1>
      </main>
    </>
  );
}


