import NavBar from "src/components/navbar";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
    const { data, isLoading } = api.post.getAllByUser.useQuery();
  return (
    <>
      <Head>
        <title>Machado</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-grow flex-col items-center bg-gradient-to-b from-amber-600 to-slate-800">
      
      <NavBar />
      <h1>stats</h1>
      { isLoading ? 
          "carregando..." : 
          data?.map((post) => { return <> <br/> {post.name} </>}) 
      }
        
      </main>
    </>
  );
}


